language: node_js
cache:
  yarn: true
  directories:
    - ~/bin
    - ~/opt
script:
  - yarn lint
  - yarn test
after_success:
  - bash ./deploy/publish_to_npm.sh
  - bash ./deploy/deploy_to_gcp.sh
  - bash ./deploy/deploy_to_ghpages.sh
env:
  global:
  - SOURCE_BRANCH: master
  - COMMIT_AUTHOR_NAME: Travis CI
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
