language: node_js
cache:
  yarn: true
  directories:
  - "~/bin"
  - "~/opt"
branches:
  only:
    - master
before_script:
- yarn ci:setup
script:
- yarn lint
- yarn ci:test
after_success:
# - bash scripts/publish_packages.sh
- bash scripts/publish_site.sh
env:
  global:
  - SOURCE_BRANCH: master
  - STORAGE_BUCKET: axiom.platform-prod.gcp0.bwcom.net
  - secure: StfqdApovGCO2Hx5HVXuGo9XUtzCehbs1IEA5ovE+zDOZXsb5ok3xvSLutqZrYk0IqoMz2r8iqjGHoykOsJQIMsw2o/pWi4HCvrJgj8PJ7qWZ/xUrDDw4oGQju4uy7le43tyjTWxNuSdubsxjax7ZU74GfrJiIz3ofgRVAeSldAGpe9O+MR7edCAGoNyg9j0hY9QOAAzqe6azjqZVAFuDXsgzKNYT5DeafPAATCaFTaN93Mh+/B6vZt8kpx1eExh516NEYgg37JUKKXk5UJ6hl+pMUwsIkNyBByQds0huFlV/Z7e1+jPbRFZXEGixCxxKE9/9xVhZApR4yBHrvXUa1CpshF5EwIjxDRDpM/LWI5mzPLtULDswFYvQJnQQfaMiyMaya3aXb8ETD7+mP3N89S7BMJs3IANHgi2EYf+NCMAS3SFgBRGwE+GKjFuITGs56CteOFqH/dGJ2RrF7NewI3IXP/tUBR4/WZafagGfMSg5HF7lWGuVZaehtwARYRlvFrUqLxLHcqxOiDIU2m5jk/8kzNzSLGxl/7EPJayoCGJxzUBjVP5g0KQnmapnrhKQHjmhFMpFLax4kVaJtEsCw1bSfAgtOpicbs1+oQmbAlSt7YG0oJjRgyWwzCm05QWRe8JlowPoo3c4mbDa5+dqzxFOqzcXI2638wOAlt6z5k=
